server:
  port: 80
spring:
  application:
    name: freemarker-service
  freemarker:
    # 设置模板后缀名
    suffix: .ftl
    # 设置文档类型
    content-type: text/html
    # 设置页面编码格式
    charset: UTF-8
    # 设置页面缓存
    cache: false

  # 设置静态文件路径，js,css等
  mvc:
    static-path-pattern: /static/**